// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD1R08wsntkHqGjJ2dde2uwD-d8DsAH9WU',
    appId: '1:270847118583:web:8df9735d22fd593282d7f2',
    messagingSenderId: '270847118583',
    projectId: 'agentia-4cb78',
    authDomain: 'agentia-4cb78.firebaseapp.com',
    storageBucket: 'agentia-4cb78.firebasestorage.app',
    measurementId: 'G-96FB4S2YFF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD2M7gCJE8YwFBJ4VV8FrJ72ZdHYA1zlk8',
    appId: '1:270847118583:android:ab6a893da555fe5782d7f2',
    messagingSenderId: '270847118583',
    projectId: 'agentia-4cb78',
    storageBucket: 'agentia-4cb78.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyASSAY1RBaYi4_dU9rCnCcrf1DuS7PgCLA',
    appId: '1:270847118583:ios:fbbad1e295f27d6b82d7f2',
    messagingSenderId: '270847118583',
    projectId: 'agentia-4cb78',
    storageBucket: 'agentia-4cb78.firebasestorage.app',
    iosClientId: '270847118583-o8fpr5e9saqf6r3qlu9919pfnip37tph.apps.googleusercontent.com',
    iosBundleId: 'com.agentai.ios',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyASSAY1RBaYi4_dU9rCnCcrf1DuS7PgCLA',
    appId: '1:270847118583:ios:3ebbdd90f0f641c082d7f2',
    messagingSenderId: '270847118583',
    projectId: 'agentia-4cb78',
    storageBucket: 'agentia-4cb78.firebasestorage.app',
    iosClientId: '270847118583-l94s335pu4nmsfukhbrr5irdjgevq0hc.apps.googleusercontent.com',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD1R08wsntkHqGjJ2dde2uwD-d8DsAH9WU',
    appId: '1:270847118583:web:a7a5461912381e7382d7f2',
    messagingSenderId: '270847118583',
    projectId: 'agentia-4cb78',
    authDomain: 'agentia-4cb78.firebaseapp.com',
    storageBucket: 'agentia-4cb78.firebasestorage.app',
    measurementId: 'G-WG8TJGT3BC',
  );
}
